name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cached_network_image: ^3.3.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  fonts:
    - family: Arimo
      fonts: 
        - asset: fonts/Arimo-Regular.ttf
          weight: 400
    - family: Pacifico
      fonts: 
        - asset: fonts/Pacifico-Regular.ttf
          weight: 400

    - family: DancingScript
      fonts:
        - asset: fonts/DancingScript-Regular.ttf
          weight: 400
        - asset: fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: fonts/DancingScript-SemiBold.ttf
          weight: 600
        - asset: fonts/DancingScript-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true  
  image_path: "assets/icons/app_icon.png"